name: Update Top Languages

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update-langs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Generate Top Languages card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=Thang4869&layout=compact&theme=react&hide_border=false&bg_color=0D1117&title_color=84B179&text_color=888888&border_color=444444
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/top-langs.svg
          git commit -m "Update top languages card" || exit 0
          git push
