name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }} # Dùng token hệ thống để đẩy ảnh

          # Cấu hình hiển thị
          user: Thang4869
          template: classic
          base: "" # Ẩn Header danh sách dài dằng dặc nãy đi
          config_timezone: Asia/Ho_Chi_Minh
          
          # PLUGIN HABITS (Đây là cái tạo ra Radar Chart)
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: radar # Ép kiểu về Mạng nhện
          
          # PLUGIN LANGUAGES (Bổ trợ thêm thông tin ngôn ngữ bên dưới)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          
          # PHẦN QUAN TRỌNG: Tránh lỗi 'remaining' và tối ưu render
          config_display: columns
          output_action: commit
          delay: 120 # Đợi 2 phút để đảm bảo API không bị nghẽn
