name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Thang4869
          template: classic
          base: ""
          config_timezone: Asia/Ho_Chi_Minh
          
          # PLUGIN HABITS (Radar Chart)
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: radar
          
          # Cấu hình hiển thị tránh lỗi API
          config_display: columns
          output_action: commit
