name: Metrics
on:
  schedule: [{cron: "0 */12 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Sử dụng @master để fix lỗi 'remaining'
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Cấu hình hiển thị
          user: Thang4869
          template: classic
          base: "" # Ẩn Header để chỉ hiện biểu đồ
          config_timezone: Asia/Ho_Chi_Minh
          
          # PLUGIN HABITS (Chìa khóa để ra Radar Chart)
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: radar # Ép kiểu hiển thị mạng nhện
